# Generated by Django 4.1.3 on 2023-01-16 10:28

from django.db import migrations, models
import number_classifier.upload_image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumbersImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=number_classifier.upload_image.upload_to)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
