# Generated by Django 4.1.3 on 2023-01-16 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number_classifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbersimage',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='numbersimage',
            name='creation_time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 16, 13, 42, 32, 913453)),
        ),
    ]
