# Generated by Django 4.1.3 on 2023-01-16 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number_classifier', '0002_remove_numbersimage_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbersimage',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='numbersimage',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 16, 13, 47, 30, 305332)),
        ),
    ]
